---

################################
# DOMAIN
################################

  ## prowlarr
prowlarr_traefik_subdomain: '{{ prowlarr_basics_name }}'
prowlarr_traefik_domain: ''
prowlarr_traefik_port: '{{ prowlarr_ports_cont }}'

  ## prometheus
prowlarr_prometheus_traefik_subdomain: '{{ prowlarr_prometheus_basics_name }}'
prowlarr_prometheus_traefik_domain: '{{ prowlarr_traefik_domain }}'
prowlarr_prometheus_traefik_port: '{{ prowlarr_prometheus_ports_cont }}'

################################
# NETWORK
################################

prowlarr_traefik_network: 'traefik_proxy'
prowlarr_traefik_network_driver: 'bridge'  ## only required if network doesn't exist
prowlarr_traefik_network_subnet: ''  ## only required if network doesn't exist

################################
# TLS
################################

prowlarr_traefik_tls_certresolver: 'dns-cloudflare'
prowlarr_traefik_tls_options: 'tls-opts@file'

################################
# ROUTER (HTTP)
################################

  ## prowlarr
prowlarr_traefik_http_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
prowlarr_traefik_http_rule: 'Host(`{{ prowlarr_traefik_subdomain }}.{{ prowlarr_traefik_domain }}`)'
prowlarr_traefik_http_priority: '20'

prowlarr_traefik_http_api_middlewares: 'globalHeaders@file,redirect-to-https@docker,autodetect@docker,gzip@docker,robotHeaders@file'
prowlarr_traefik_http_api_rule: '{{ prowlarr_traefik_http_rule + " && (PathRegexp(`/[0-9]+/api`) || PathRegexp(`/[0-9]+/download`) || PathPrefix(`/api`) || PathPrefix(`/ping`))" }}'
prowlarr_traefik_http_api_priority: '30'

  ## prometheus
prowlarr_prometheus_traefik_http_middlewares: '{{ prowlarr_traefik_http_middlewares }}'
prowlarr_prometheus_traefik_http_rule: 'Host(`{{ prowlarr_prometheus_traefik_subdomain }}.{{ prowlarr_prometheus_traefik_domain }}`)'
prowlarr_prometheus_traefik_http_priority: '{{ prowlarr_traefik_http_priority }}'

################################
# ROUTER (HTTPS)
################################

  ## prowlarr
prowlarr_traefik_https_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
prowlarr_traefik_https_rule: 'Host(`{{ prowlarr_traefik_subdomain }}.{{ prowlarr_traefik_domain }}`)'
prowlarr_traefik_https_priority: '20'

prowlarr_traefik_https_api_middlewares: 'globalHeaders@file,secureHeaders@file,autodetect@docker,gzip@docker,robotHeaders@file,hsts@file'
prowlarr_traefik_https_api_rule: '{{ prowlarr_traefik_https_rule + " && (PathRegexp(`/[0-9]+/api`) || PathRegexp(`/[0-9]+/download`) || PathPrefix(`/api`) || PathPrefix(`/ping`))" }}'
prowlarr_traefik_https_api_priority: '30'

  ## prometheus
prowlarr_prometheus_traefik_https_middlewares: '{{ prowlarr_traefik_https_middlewares }}'
prowlarr_prometheus_traefik_https_rule: 'Host(`{{ prowlarr_prometheus_traefik_subdomain }}.{{ prowlarr_prometheus_traefik_domain }}`)'
prowlarr_prometheus_traefik_https_priority: '{{ prowlarr_traefik_https_priority }}'

################################
# THEME-PARK
################################

prowlarr_traefik_themepark_theme: 'hotpink'