---

################################
# BASICS
################################

prowlarr_prometheus_basics_name: 'prometheus'
prowlarr_prometheus_basics_image_repo: 'prom/prometheus'
prowlarr_prometheus_basics_image_tag: 'latest'
prowlarr_prometheus_basics_restart_policy: 'unless-stopped'

################################
# NETWORK
################################

prowlarr_prometheus_network: 'prometheus'
prowlarr_prometheus_network_driver: 'bridge'
prowlarr_prometheus_network_subnet: '172.42.0.0/24'

################################
# ENV
################################

prowlarr_prometheus_env_timezone: 'Australia/Melbourne'
prowlarr_prometheus_env_puid: 'ansible'
prowlarr_prometheus_env_pgid: 'ansible'

################################
# PORTS
################################

prowlarr_prometheus_ports_host: '9090'
prowlarr_prometheus_ports_cont: '9090'

################################
# PATHS
################################

prowlarr_prometheus_paths_folder: '{{ prowlarr_prometheus_basics_name }}'  # name of prometheus config folder
prowlarr_prometheus_paths_location: '/opt/{{ prowlarr_prometheus_paths_folder }}'  # path of prometheus config folder
prowlarr_prometheus_paths_data_location: '{{ prowlarr_prometheus_paths_location }}/data'  # path where prometheus metrics are stored
                                                                                      # be mindful of metrics retention and size

################################
# BINDS
################################

prowlarr_prometheus_binds_config_mapping:
  - '{{ prowlarr_prometheus_paths_location }}/prometheus.yml:/etc/prometheus/prometheus.yml'

prowlarr_prometheus_binds_data_mapping: 
  - '{{ prowlarr_prometheus_paths_data_location }}:/data'

################################
# TRAEFIK
################################
  
prowlarr_prometheus_traefik_subdomain: '{{ prowlarr_prometheus_basics_name }}'
prowlarr_prometheus_traefik_domain: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31626230313539326435393162353635656434306466366632333436366162303035613536666130
          6436633630346533636636313130353733656230626464390a383832326334613666373739623539
          64343537363262663437623930383737313335356564396264306132663961653130346362323666
          3132356537383833330a376163666236373835383134663961663663613735326266333838393138
          64366364373361343435363934613531393034343436396561626231613735613264
prowlarr_prometheus_traefik_network: 'traefik_proxy'
prowlarr_prometheus_traefik_port: '9090'

################################
# CLOUDFLARE
################################

prowlarr_prometheus_cloudflare_record_type: 'A'  ## A (IPV4), AAAA (IPV6), CNAME, etc
prowlarr_prometheus_cloudflare_proxy: 'true'  ## true for cloudflare DNS SSL
prowlarr_prometheus_cloudflare_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39656635653830373638396637393063363862303062383336363836643531386233656336393562
          3136396663383035353739633665373734643661613738350a616631326364306430616235643163
          37316435613362383935623736306234343262643766393936333936623064663539366233653031
          6636323765306366630a386437326338396138623464386430646231316136303839323835353535
          30363666333263323837316464363732393963386332666535313765303634616164326239333435
          3866636365383861326237346234636261363664663861323934

################################
# METRICS
################################

prowlarr_prometheus_metrics_retention_time: '15d'
prowlarr_prometheus_metrics_retention_size: '0'  ## 0 for disabled. Use size units, i.e, 500MB, 2GB, 1TB, etc.

################################
# EXPORTER
################################

prowlarr_prometheus_exporter_name: '{{ prowlarr_basics_name }}_exporter'
prowlarr_prometheus_exporter_image_repo: 'ghcr.io/onedr0p/exportarr'
prowlarr_prometheus_exporter_image_tag: 'v2.0.1'
prowlarr_prometheus_exporter_restart_policy: 'unless-stopped'
prowlarr_prometheus_exporter_host_port: '9710' 
prowlarr_prometheus_exporter_cont_port: '9710'

