---

################################
# BASICS
################################

prowlarr_prometheus_basics_name: 'prometheus'
prowlarr_prometheus_basics_image_repo: 'prom/prometheus'
prowlarr_prometheus_basics_image_tag: 'latest'
prowlarr_prometheus_basics_restart_policy: 'unless-stopped'

################################
# NETWORK
################################

prowlarr_prometheus_network: 'prometheus'
prowlarr_prometheus_network_driver: ''
prowlarr_prometheus_network_subnet: ''

################################
# ENV
################################

prowlarr_prometheus_env_timezone: ''
prowlarr_prometheus_env_puid: ''
prowlarr_prometheus_env_pgid: ''

################################
# PORTS
################################

prowlarr_prometheus_ports_host: '9090'
prowlarr_prometheus_ports_cont: '9090'

################################
# PATHS
################################

prowlarr_prometheus_paths_folder: '{{ prowlarr_prometheus_basics_name }}'  # name of prometheus config folder
prowlarr_prometheus_paths_location: '/opt/{{ prowlarr_prometheus_paths_folder }}'  # path of prometheus config folder
prowlarr_prometheus_paths_data_location: '{{ prowlarr_prometheus_paths_location }}/data'  # path where prometheus metrics are stored
                                                                                      # be mindful of metrics retention and size

################################
# BINDS
################################

prowlarr_prometheus_binds_config_mapping:
  - '{{ prowlarr_prometheus_paths_location }}/prometheus.yml:/etc/prometheus/prometheus.yml'

prowlarr_prometheus_binds_data_mapping:
  - '{{ prowlarr_prometheus_paths_data_location }}:/data'

################################
# TRAEFIK
################################

prowlarr_prometheus_traefik_subdomain: '{{ prowlarr_prometheus_basics_name }}'
prowlarr_prometheus_traefik_domain: ''
prowlarr_prometheus_traefik_network: '{{ prowlarr_traefik_network }}'
prowlarr_prometheus_traefik_port: '9090'

################################
# CLOUDFLARE
################################

prowlarr_prometheus_cloudflare_record_type: 'A'  ## A (IPV4), AAAA (IPV6), CNAME, etc
prowlarr_prometheus_cloudflare_proxy: 'true'  ## true for cloudflare DNS SSL
prowlarr_prometheus_cloudflare_api_token: ''

################################
# METRICS
################################

prowlarr_prometheus_metrics_retention_time: '15d'
prowlarr_prometheus_metrics_retention_size: '0'  ## 0 for disabled. Use size units, i.e, 500MB, 2GB, 1TB, etc.

################################
# EXPORTER
################################

prowlarr_prometheus_exporter_name: '{{ prowlarr_basics_name }}_exporter'
prowlarr_prometheus_exporter_image_repo: 'ghcr.io/onedr0p/exportarr'
prowlarr_prometheus_exporter_image_tag: 'v2.0.1'
prowlarr_prometheus_exporter_restart_policy: 'unless-stopped'
prowlarr_prometheus_exporter_env_puid: 'ansible'
prowlarr_prometheus_exporter_env_pgid: 'ansible'
prowlarr_prometheus_exporter_env_timezone: 'Australia/Melbourne'
prowlarr_prometheus_exporter_host_port: '9710'
prowlarr_prometheus_exporter_cont_port: '9710'
