---

################################
# DNS
################################

prowlarr_prometheus_cloudflare_record_type: 'A'  ## A (IPV4), AAAA (IPV6), CNAME, etc
prowlarr_prometheus_cloudflare_proxy: 'true'  ## true for cloudflare DNS SSL
prowlarr_prometheus_cloudflare_api_token: ''